analyze <- function(filename) {
  # Plots the average, min, and max inflammation over time.
  # Input is character string of a csv file.
  dat <- read.csv(file = filename, header = FALSE)
  avg_day_inflammation <- apply(dat, 2, mean)
  plot(avg_day_inflammation)
  max_day_inflammation <- apply(dat, 2, max)
  plot(max_day_inflammation)
  min_day_inflammation <- apply(dat, 2, min)
  plot(min_day_inflammation)
}

analyze_all <- function(folder = "data", pattern) {
  # Runs the function analyze for each file in the given folder
  # that contains the given pattern.
  filenames <- list.files(path = folder, pattern = pattern, full.names = TRUE)
  for (f in filenames) {
    analyze(f)
  }
}

# The function pdf redirects all the plots generated by R into a pdf file,
# which in this case we have named “inflammation-01.pdf”. After we are done
# generating the plots to be saved in the pdf file, we stop R from redirecting
# plots with the function dev.off.
pdf("data/inflammation-01.pdf")
analyze("data/inflammation-01.csv")
dev.off()

# NA represents the absence of a value, we will not be able to test its equality 
# or inequality with another value. Such tests always return NA:
a<- NA
a==1
a==NA
if(a==NA){
  print("Hi")
}
# To solve this issue, we need to use the dedicated is.na() function
is.na(a)
if(is.na(a)){
  print("Hi")
}

# Write a function plot_dist that plots a boxplot if the length of the vector 
# is greater than a specified threshold and a stripchart otherwise. To do this
# you’ll use the R functions boxplot and stripchart.
plot_dist <- function(vec_len,threshold){
  if(length(vec_len)>threshold){
    boxplot(vec_len)
  }
  else{
    stripchart(vec_len)
  }
}
dat <- read.csv("data/inflammation-01.csv", header = FALSE)
plot_dist(dat[, 10], threshold = 10)
plot_dist(dat[1:5, 10], threshold = 10)  # samples (rows) 1-5 on day (column) 10

# One of your collaborators prefers to see the distributions of the larger 
# vectors as a histogram instead of as a boxplot. In order to choose between a 
# histogram and a boxplot we will edit the function plot_dist and add an 
# additional argument use_boxplot. By default we will set use_boxplot to TRUE 
# which will create a boxplot when the vector is longer than threshold. When 
# use_boxplot is set to FALSE, plot_dist will instead plot a histogram for 
# the larger vectors. As before, if the length of the vector is shorter than 
# threshold, plot_dist will create a stripchart. A histogram is made with the 
# hist command in R.
plot_dist <- function(vec_len,threshold,use_boxplot = TRUE){
  if(length(vec_len)>threshold && use_boxplot){
    boxplot(vec_len)
  }
  else if(length(vec_len)>threshold && !use_boxplot){
      hist(vec_len)
  }
  else{
    stripchart(vec_len)
  }
}
dat <- read.csv("data/inflammation-01.csv", header = FALSE)
plot_dist(dat[, 10], threshold = 10, use_boxplot = TRUE)
plot_dist(dat[, 10], threshold = 10, use_boxplot = FALSE)  # day (column) 10 - create histogram
plot_dist(dat[1:5, 10], threshold = 10)                    # samples (rows) 1-5 on day (column) 10

# Find the file containing the patient with the highest average inflammation 
# score. Print the file name, the patient number (row number) and the value of 
# the maximum average inflammation score.
# 
# Tips:
#   
# Use variables to store the maximum average and update it as you go through 
# files and patients.
# You can use nested loops (one loop is inside the other) to go through the 
# files as well as through the patients in each file (every row).
all_files <- list.files(path = "data", pattern = "inflammation-[0-9]{2}.csv",
                        full.names = TRUE)
file_max <- 0
patient_max <- 0
avg_inf_score_max <- 0
for (f in all_files){
  f_read <- read.csv(f,header = FALSE)
  avg_inf_score <- apply(f_read, 1, mean)
  patient_avg_index <- 0
  for(patient_index in 1:length(avg_inf_score)){
    patient_avg_index <- avg_inf_score[patient_index]
    if(patient_avg_index > avg_inf_score_max) {
      avg_inf_score_max <- patient_avg_index
      file_max <- f
      patient_max <- patient_index
    }
  }
}
print(file_max)
print(patient_max)
print(avg_inf_score_max)

analyze <- function(filename, output = NULL) {
  # Plots the average, min, and max inflammation over time.
  # Input:
  #    filename: character string of a csv file
  #    output: character string of pdf file for saving
  if (!is.null(output)) {
    pdf(output)
  }
  dat <- read.csv(file = filename, header = FALSE)
  avg_day_inflammation <- apply(dat, 2, mean)
  plot(avg_day_inflammation)
  max_day_inflammation <- apply(dat, 2, max)
  plot(max_day_inflammation)
  min_day_inflammation <- apply(dat, 2, min)
  plot(min_day_inflammation)
  if (!is.null(output)) {
    dev.off()
  }
}

analyze("data/inflammation-01.csv")
analyze("data/inflammation-01.csv", output = "inflammation-01.pdf")
analyze("data/inflammation-01.csv", output = "results/inflammation-01.pdf")

analyze_all <- function(pattern) {
  #Storing directory names
  data_dir <- "data"
  results_dir <- "results"
  # Runs the function analyze for each file in the given folder
  # that contains the given pattern.
  filenames <- list.files(path = data_dir, pattern = pattern)
  for (f in filenames) {
    pdf_name <- file.path(results_dir,sub("csv","pdf",f))
    analyze(file.path(data_dir,f),output = pdf_name)
  }
}
analyze_all("inflammation.*csv")

analyze <- function(filename,output=NULL) {
  # Plots the average, min, and max inflammation over time.
  # Input is character string of a csv file.
  if(!is.null(output)){
    pdf(output)
  }
  dat <- read.csv(file = filename, header = FALSE)
  avg_day_inflammation <- apply(dat, 2, mean)
  plot(avg_day_inflammation,type = "l")
  max_day_inflammation <- apply(dat, 2, max)
  plot(max_day_inflammation,type = "l")
  min_day_inflammation <- apply(dat, 2, min)
  plot(min_day_inflammation,type = "l")
  if(!is.null(output)){
    dev.off()
  }
}